#! /usr/bin/env php
<?php
declare(strict_types=1);
\error_reporting(-1);

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/functions.php';

use Symfony\Component\Finder\Finder;


//******************************************************************************
// Update files

/**
 * This will reformat the XML files and save the changes to disk.
 */

$__files__ = [
    'pdepend.xml.dist',
    'phpcs.xml',
    'phpmd.xml.dist',
    'phpunit.xml.dist',
];

foreach ($__files__ as $__f__) {
    $finder = Finder::create()
        ->files()
        ->name($__f__)
        ->depth('< 2')
        ->in(dirname(__DIR__))
        ->notPath('vendor')
    ;

    foreach ($finder as $file) {
        $path = $file->getRealPath();

        // First pass
        $domDocument = new DOMDocument('1.0');
        $domDocument->recover             = true;
        $domDocument->formatOutput        = true;
        $domDocument->preserveWhiteSpace  = false;
        $domDocument->resolveExternals    = false;
        $domDocument->substituteEntities  = false;
        $domDocument->strictErrorChecking = false;
        $domDocument->validateOnParse     = false;

        $domDocument->load($path);
        $domDocument->save($path);

        // Second pass
        $content = file_get_contents($path);
        $content = preg_replace('/&gt;/i', '>', $content);
        file_put_contents($path, $content);

        echo sprintf('Completed %s', $path) . PHP_EOL;
    }

    unset($finder);
}
