#! /usr/bin/env php
<?php
declare(strict_types=1);
\error_reporting(-1);

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/functions.php';

use Symfony\Component\Finder\Finder;


//******************************************************************************
// Update composer.json files

$jsonOpts = JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE;

$finder = Finder::create()
    ->files()
    ->name('composer.json')
    ->depth('< 2')
    ->in(dirname(__DIR__))
    ->notPath('vendor')
;

foreach ($finder as $file) {
    echo sprintf('Processing %s', $file->getRealPath()) . PHP_EOL;

    // Take the existing file and overlay what we want
    $json    = json_decode(file_get_contents($file->getRealPath()), true);
    $overlay = json_decode(file_get_contents(__DIR__ . '/templates/composer.json.tmpl'), true);
    $merged  = array_merge_recursive_adv($json, $overlay);

    // Delete the things we want to remove
    unset($merged['require-dev']['codeclimate/php-test-reporter']);
    unset($merged['require-dev']['skyzyx/utility-pack']);

    unset($merged['require']['skyzyx/utility-pack']);

    // Sort the results
    natkeysort($merged['config']);
    composersort($merged['require']);
    natkeysort($merged['require-dev']);
    natkeysort($merged['suggest']);

    // Write the file back to disk
    file_put_contents($file->getRealPath(), json_encode($merged, $jsonOpts) . PHP_EOL);

    echo sprintf('Completed %s', $file->getRealPath()) . PHP_EOL;
}
