#! /usr/bin/env php
<?php
declare(strict_types=1);
\error_reporting(-1);

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/functions.php';

use Symfony\Component\Finder\Finder;


//******************************************************************************
// Update Makefile

$finder = Finder::create()
    ->files()
    ->name('Makefile.tmpl')
    ->depth('< 3')
    ->in(dirname(__DIR__))
    ->notPath('vendor')
;

foreach ($finder as $file) {
    $template = file_get_contents($file->getRealPath());
    $writeTo  = sprintf(
        '%s/Makefile',
        dirname(
            dirname($file->getRealPath())
        )
    );

    echo sprintf('Updating %s', $writeTo) . PHP_EOL;

    $contents = preg_replace_callback('/@@([^@]+)@@/S', function(array $matches): string {
        [$tag, $file] = $matches;
        return trim(
            file_get_contents(
                sprintf('%s/templates/Makefile-%s.tmpl', __DIR__, $file)
            )
        );
    }, $template, -1) . PHP_EOL;

    // Write the file back to disk
    file_put_contents($writeTo, $contents);
}
